production:
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  partner_id: "PARTNER_ID"
  uri: "https://agcod-v2.amazon.com"

development: &development
  access_key: "YOUR_DEV_ACCESS_KEY"
  secret_key: "YOUR_DEV_SECRET_KEY"
  partner_id: "PARTNER_ID"
  uri: "https://agcod-v2-gamma.amazon.com"

test:
  <<: *development
